import json
import re

from groq import Groq

import config

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=config.GROQ_API_KEY)
    return _client


PROMPT = """You are an assistant helping a creative-writing platform assess whether a piece of text was likely written by a human or generated by an AI language model.

Consider: semantic coherence, idiosyncrasy of voice, presence of specific/personal detail vs. generic phrasing, hedging/qualifying language patterns common in LLM output, and overall naturalness.

Respond with ONLY a JSON object, no other text, in exactly this format:
{{"ai_probability": <float between 0.0 and 1.0, where 1.0 = certainly AI-generated and 0.0 = certainly human-written>, "reasoning": "<one sentence explanation>"}}

Text to assess:
\"\"\"{text}\"\"\"
"""


def _extract_json(raw: str) -> dict:
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON object found in LLM response: {raw!r}")
    return json.loads(match.group(0))


def llm_signal(text: str) -> dict:
    """Returns {"ai_probability": float, "reasoning": str}.

    Falls back to a neutral 0.5 score if no API key is configured or the
    call fails, so the rest of the pipeline still runs end-to-end.
    """
    if not config.GROQ_API_KEY:
        return {
            "ai_probability": 0.5,
            "reasoning": "No GROQ_API_KEY configured; neutral fallback score used.",
        }

    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=config.LLM_MODEL,
            messages=[{"role": "user", "content": PROMPT.format(text=text)}],
            temperature=0.0,
            max_tokens=200,
        )
        raw = response.choices[0].message.content
        parsed = _extract_json(raw)
        ai_probability = float(parsed["ai_probability"])
        ai_probability = max(0.0, min(1.0, ai_probability))
        return {
            "ai_probability": ai_probability,
            "reasoning": str(parsed.get("reasoning", "")),
        }
    except Exception as exc:
        return {
            "ai_probability": 0.5,
            "reasoning": f"LLM signal failed, neutral fallback used: {exc}",
        }
